image: python:3.7

include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - test
  - register
  - deploy

# It runs only when a push is executed in a merge request and an ontology file has changed
# or when a commit is executed in develop branch and an ontology file has changed
# or when a new tag is pushed
test-ontologies-on-merge-request:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      changes:
        - ontologies/bbp/*
      when: always
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - pytest tests/test_ontologies.py
  before_script:
    - pip install -r requirements.txt

# It runs only when a commit is done on develop branch and the pipeline was triggered from a Merge Request
# and an ontology file has changed
register-on-staging-environment:
  stage: register
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      changes:
        - ontologies/bbp/*
      when: on_success
  script:
    - git fetch
    - CHANGED_FILES=$(git diff --name-only HEAD~1)
    - python register_ontologies.py --environment staging --token $NEXUS_TOKEN_STAGING --files $CHANGED_FILES
  before_script:
    - pip install -r requirements.txt

# It runs only when a new tag is pushed.
# It executes ontologies registration for the files changed between this version and the previous one
register-on-production-environment:
  stage: register
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  script:
    - echo $CI_COMMIT_TAG
    - python register_ontologies.py --environment production --token $NEXUS_TOKEN_PRODUCTION --tag $CI_COMMIT_TAG
  before_script:
    - pip install -r requirements.txt

# It runs only when a new tag is pushed
# It executes deployment of ontologies documentation to Openshift
deploy-docs-in-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      changes:
        - ontologies/bbp/*
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GITLAB_DEPLOY_TOKEN=${GITLAB_DEPLOY_TOKEN} --build-arg GITLAB_DEPLOY_PASSWORD=${GITLAB_DEPLOY_PASSWORD}"