image: python:3.7

include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - test
  - register
  - generate
  - deploy

# TEST STAGE

# It runs only when a push is executed in a merge request and an ontology file has changed
# or when a commit is executed in develop branch and an ontology file has changed
# or when a new tag is pushed
test-ontologies-on-merge-request:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      when: always
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - CA_BUNDLE=$(python3 -c "import certifi; print(certifi.where())")
    - cat $BBP_CA_CERT >> $CA_BUNDLE
    - pytest tests/test_ontologies.py --token $NEXUS_TOKEN_STAGING
  before_script:
    - pip install -r requirements.txt
variables:
  KUBERNETES_HELPER_MEMORY_REQUEST: 512Mi
  KUBERNETES_HELPER_MEMORY_LIMIT: 1Gi
#    KUBERNETES_MEMORY_LIMIT: 8Gi
#    KUBERNETES_MEMORY_REQUEST: 8Gi


# REGISTER STAGE

# It runs only when a commit is done on develop branch and the pipeline was triggered from a Merge Request
# and an ontology file has changed
register-on-staging-environment:
  stage: register
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      changes:
          - ./ontologies/bbp/*.ttl
          - ./shapes/**/*.json
          - ./jsonldcontext/*.json
          - ./texts/*.json
          - ./register_ontologies.py
          - ./bmo_tools/ontologies.py
          - ./bmo_tools/utils.py
      when: on_success
  script:
    - CA_BUNDLE=$(python3 -c "import certifi; print(certifi.where())")
    - cat $BBP_CA_CERT >> $CA_BUNDLE
    - python register_ontologies.py --environment staging --bucket neurosciencegraph/datamodels --ontology_dir './ontologies/bbp/*.ttl' --schema_dir './shapes/**/*.json' --token $NEXUS_TOKEN_STAGING
  before_script:
    - pip install -r requirements.txt

# It runs only when a new tag is pushed.
# It executes ontologies registration for the files changed between this version and the previous one
register-on-production-environment:
  stage: register
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  script:
    - echo $CI_COMMIT_TAG
    - python register_ontologies.py --environment production --bucket neurosciencegraph/datamodels --ontology_dir './ontologies/bbp/*.ttl' --schema_dir './shapes/**/*.json' --token $NEXUS_TOKEN_PRODUCTION --tag $CI_COMMIT_TAG
  before_script:
    - pip install -r requirements.txt

# GENERATE STAGE

# Building documentation for sphinx and ontodocs
# The docs are generated and stored in artifacts in order to be used in the deploy stage

# Generate ontodocs documentation and stores the artifact under /visualization
generate-ontodocs-documentation:
  stage: generate
  image: python:3.7
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
  script:
    - pip install git+https://$GITLAB_DEPLOY_TOKEN:$GITLAB_DEPLOY_PASSWORD@bbpgitlab.epfl.ch/dke/apps/ontodocs.git
    - mkdir visualization
    - ontospy gendocs ./ontologies/bbp --theme lumen --outputpath ./visualization --title "Brain Modeling Ontology" --preflabel "label" -v
  artifacts:
    paths:
      - visualization
  variables:
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

# Generate sphinx documentation and stores the artifact under /generated/html
generate-sphinx-documentation:
  stage: generate
  image: python:3.7
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
  script:
    - pip install .[docs]
    - sphinx-build -T --keep-going -b html -d _build/doctrees -c ./docs/source -D language=en ./docs/source generated/html
  artifacts:
    paths:
      - generated/html
  variables:
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

# DEPLOY STAGE

# Deploys the documentation to Openshift using Kaniko

# Executes deployment of ontodocs documentation to bbp-dke-staging Openshift
deploy-ontodocs-in-staging-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-ontodocs-documentation
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=visualization"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/ontodocs-staging


# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-sphinx-documentation-in-staging-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-sphinx-documentation
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-staging
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

# Executes deployment of ontodocs documentation to bbp-dke-production Openshift
deploy-ontodocs-in-production-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-ontodocs-documentation
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=visualization"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/ontodocs-production

# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-sphinx-documentation-in-production-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-sphinx-documentation
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-production
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi
