Model:
  name: RdfModel
  origin: directory
  source: "./shapes"
  context:
    iri: "./jsonldcontext/neuroshapes_org.json"
    bucket: "./jsonldcontext"

Store:
  name: BlueBrainNexus
  model:
    name: RdfModel
  endpoint: https://staging.nexus.ocp.bbp.epfl.ch/v1
  searchendpoints:
    sparql:
      endpoint: "https://bluebrain.github.io/nexus/vocabulary/defaultSparqlIndex"
  vocabulary:
    metadata:
      iri: "https://bluebrain.github.io/nexus/contexts/metadata.json"
      local_iri: "https://bluebrainnexus.io/contexts/metadata.json"
    namespace: "https://bluebrain.github.io/nexus/vocabulary/"
    deprecated_property: "https://bluebrain.github.io/nexus/vocabulary/deprecated"
    project_property: "https://bluebrain.github.io/nexus/vocabulary/project"
  max_connection: 50
  versioned_id_template: "{x.id}?rev={x._store_metadata._rev}"
  file_resource_mapping: config/mappings/file-to-resource-mapping.hjson

Resolvers:
  ontology:
    - resolver: OntologyResolver
      origin: store
      source: BlueBrainNexus
      targets:
        - identifier: terms
          bucket: neurosciencegraph/datamodels
        - identifier: CellType
          bucket: neurosciencegraph/datamodels
          filters:
            - path: subClassOf*.id
              value: BrainCellType
        - identifier: BrainRegion
          bucket: neurosciencegraph/datamodels
          filters:
            - path: subClassOf*.id
              value: BrainRegion
        - identifier: Species
          bucket: neurosciencegraph/datamodels
          filters:
            - path: subClassOf*.id
              value: Species
      result_resource_mapping: config/mappings/term-to-resource-mapping.hjson
  agent:
    - resolver: AgentResolver
      origin: store
      source: BlueBrainNexus
      targets:
        - identifier: agents
          bucket: bbp/agents
      result_resource_mapping: config/mappings/agent-to-resource-mapping.hjson

Formatters:
  identifier: https://bbp.epfl.ch/neurosciencegraph/data/{}/{}
  ontology: https://bbp.epfl.ch/ontologies/{}/{}
  class: https://bbp.epfl.ch/ontologies/{}/{}/{}

